name: imcaptionnet-cpu
dependencies: 
  - python=3.6.5
  - pip:
    - tensorflow
    - h5py
    - Pillow
    - Cython
    - git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
    - matplotlib