name: imcaptionnet-gpu
dependencies: 
  - python=3.6.5
  - pip:
    - tensorflow-gpu
    - h5py
    - Pillow
    - git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
    - git+https://github.com/sleighsoft/pycocoevalcap.git
    - Cython
    - numpy
    - matplotlib
    - nltk